cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'coreutils'
brew 'git'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'atom'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'hugin'
cask 'libreoffice'
cask 'seashore'
cask 'sublime-text3'
cask 'vlc'
