cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'coreutils'
brew 'gdbm', args: ['universal']
brew 'git'
brew 'imagemagick'
brew 'jenv'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'npm'
brew 'readline', args: ['universal']
brew 'oath-toolkit'
brew 'p7zip'
brew 'postgresql'
brew 'sqlite', args: ['universal']
brew 'unrar'

brew 'python'
brew 'python3'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'ruby-build'
brew 'rbenv'
brew 'spark'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# Development tools
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
#brew 'mysql-connector-c'
brew 'mysql'
brew 'cairo'
brew 'pango'
brew 'geoip'

cask 'dockertoolbox'

cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'hugin'
cask 'libreoffice'
cask 'java6'
cask 'java7'
cask 'seashore'
cask 'sequel-pro'
cask 'sizeup'
cask 'skype'
cask 'sublime-text3'
cask 'telegram'
cask 'vlc'
cask 'virtualbox'

